Dev singularity
NDCLab/instruments pull request #12
Opened 2021-08-09 18:51 UTC by F-said

- created docker image file
- created singularity recipe

2021-08-12 03:03 UTC, georgebuzzell requested changes
@F-said some minor comments/questions

2021-08-12 03:03 UTC, georgebuzzell commented on container/README.md
> +The singularity image can only be built on Linux with a user that has root access. Follow [this tutorial](https://ndclab.github.io/wiki/docs/technical-docs/docker-usage.html) to build a Singularity i
does this not pose an issue for us on the hpc, given that we do not have root? @F-said

2021-08-12 03:03 UTC, georgebuzzell commented on container/README.md
> +Containerization tools such as Docker & Singularity provide the set of technologies necessary to quickly replicate system tools, libraries, data, environment variables, and more. This ensures that so
should we add a caveat that the kernel itself is not containerized, tho? i.e. singularity/docker are great, and solve a lot of issues, but are not perfect. @F-said

2021-08-12 03:03 UTC, georgebuzzell commented on container/singularity.recipe
> +	|  \ |  | |       \ /      ||  |        /   \     |   _  \
ummmm, LOVE THIS!! :) @F-said

2021-08-12 03:03 UTC, georgebuzzell commented on container/singularity.recipe
> +	 python3-pip \
ditto to comment above, pip included in conda/miniconda, no? @F-said

2021-08-16 22:29 UTC, SDOsmany commented on container/singularity.recipe
> +	 python3-pip \
@georgebuzzell I think miniconda/conda  comes with pip but he is installing pip3 which is a newer version. I think the conda pip version is pip2
@F-said is this correct?

2021-09-20 20:36 UTC, F-said commented
Comments resolved, ready for merge

2021-09-20 20:41 UTC, merged