Add ERQ to script
NDCLab/instruments pull request #130
Opened 2022-01-24 19:39 UTC by jessb0t

@F-said Please check my work on adding the ERQ!  Also, I posted a note in Slack, but I couldn't find where to set the 80% threshold for outputting scores?  Thanks! :pray:

2022-01-26 17:55 UTC, F-said requested changes

2022-01-26 17:55 UTC, F-said commented on scripts/surveys.json
> +            "score_type": "avg"
Great, that's the standard! Yes, some parameters are not obvious and I should probably consider adding them to the README. 

We should be able to place the threshold like so:

```
    "ExpSup": {
            "questions": [2, 4, 6, 9],
            "threshold": 0.8
            "score_type": "avg"
        }
```

Let me know if this helps!

2022-01-26 17:55 UTC, F-said commented on scripts/surveys.json
> +}
Just for comprehension, the acceptable params are the following

```
    score_type: String | custom_score()
                String scoretype that represents a ScoreType value. "Sum" by default.
    prev_data:  pd.DataFrame() | None
                Pandas dataframe containing previously generated data
    threshold:  float 
                Float that represents threshold to score row. 1.0 by default, which indicates all 
                questions must be answered.
    questions:  list() | None
                Which questions to select for scoring.
    rev_questions:  list() | None
                    Which questions to select for reverse scoring.
    max:    int | None
            Maximum possible value of survey answer. Must be included to guarantee correct
            reverse scoring.
    products:   list() | None
                List of products to score from "prev_data". "prev_data" must be included to score
    criteria:   list() | None  
                list of valid answers. None if any answer is valid
```

2022-01-26 19:17 UTC, jessb0t commented
Thanks, @F-said !  I updated.  I hadn't seen your notes here yet so I input the order differently...let me know if that should be corrected?  :pray:

2022-01-27 18:30 UTC, F-said approved these changes

2022-01-27 18:32 UTC, merged