Dev consent
NDCLab/instruments pull request #221
Opened 2022-04-20 20:01 UTC by jessb0t

@emach039 Could you please check my changes here to add a template consent for new study setup? 🙏

2022-04-20 20:19 UTC, emach039 commented on consent/readme.md
> +1. Upload the .zip file to REDCap.
perhaps:
Upload the .zip file to REDCap in the Designer.

this is obvious to us but unsure how clear it would be to those with less redcap experience

2022-04-20 20:22 UTC, emach039 requested changes
sans the very minor comment i made, looks good! whether or not you feel the change i suggested is necessary is up to you

2022-04-21 20:58 UTC, jessb0t commented on consent/readme.md
> +1. Upload the .zip file to REDCap.
@emach039 Change made!  Please take a look and merge if it is good!  After you merge, would you be so kind as to inform the others on #live-study-mgmt that this is now available for them?

2022-04-22 02:02 UTC, emach039 approved these changes
good!

2022-04-22 02:02 UTC, merged

2022-04-22 02:03 UTC, emach039 commented on consent/readme.md
> +1. Upload the .zip file to REDCap.
will do!